@hostname = localhost
@port = 5294
@host = http://{{hostname}}:{{port}}
@contentType = application/json

### 1. Register a new user
# @name register
POST {{host}}/api/auth/register
Content-Type: {{contentType}}

{
  "name": "john_doe",
  "email": "john@example.com",
  "password": "StrongPassword"
}

### 2. Login (to get tokens)
# @name login
POST {{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "name": "john_doe",
  "password": "StrongPassword"
}

### Store tokens from login response
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyOTQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyOTQiLCJleHAiOjE3NzQwMTQ5MDUsInN1YiI6ImVhMmU5MTEzLTliMjMtNDEwNi04Y2U4LWYzMDE5ZDA5YjBhYSIsIm5hbWUiOiJqb2huX2RvZSIsImp0aSI6ImZjZjNmZjlkLTQwMDItNDEyMy1iYmUxLTgxYjBkNTRiMWNmYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJpYXQiOjE3NzQwMTQ4NDUsIm5iZiI6MTc3NDAxNDg0NX0.xDfm3mJ8Azu_ceE1-nwbxBolW-32u-oCcKqltGHNB6s
@refreshToken = Uu780V9PxUyJdVQb26lPwA

### 3. Refresh Access Token
# @name refresh
POST {{host}}/api/auth/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "{{refreshToken}}"
}

### Update access token after refresh
@newAccessToken = {{refresh.response.body.accessToken}}

### 4. Create a new note (Requires Auth)
# @name createNote
POST {{host}}/api/notes
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "name": "My First Note",
  "content": "This is a test note content for my FSD app."
}

###
GET {{host}}/api/notes/024ec651-2c2c-4a7a-8edc-8713a297dd2a
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

### 5. Edit the note
@noteId = 024ec651-2c2c-4a7a-8edc-8713a297dd2a

PUT {{host}}/api/notes/{{noteId}}
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "name": "Updated Note Name",
  "content": "Updated content."
}